server:
  port: 8090
spring:
  application:
    name: MyResumeIntroduceService
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/myinterview?serverTimezone=UTC&useSSL=false&characterEncoding=UTF-8
  cloud:
    nacos:
      server-addr: localhost
      discovery:
        server-addr: localhost
        namespace: public